apiVersion: v1
kind: Service
metadata:
  name: digital-twin-backend-svc
  labels:
    app: digital-twin-backend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: digital-twin-backend
